// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIRYm_I1TzXYfTie6PrAfimh7RZOMC9Cg',
    appId: '1:904989064999:web:a49b2c88038fdcf43f7302',
    messagingSenderId: '904989064999',
    projectId: 'whatsapp-backend-ad7cc',
    authDomain: 'whatsapp-backend-ad7cc.firebaseapp.com',
    storageBucket: 'whatsapp-backend-ad7cc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgkiKNkfnOlrmX-LDmcsVIZguV3wra_NY',
    appId: '1:904989064999:android:1b57ab79c6ab25253f7302',
    messagingSenderId: '904989064999',
    projectId: 'whatsapp-backend-ad7cc',
    storageBucket: 'whatsapp-backend-ad7cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAl3d6kyei8BcLIQnG4O0Q0qdml4oSht4U',
    appId: '1:904989064999:ios:e5cbdb2f9809825c3f7302',
    messagingSenderId: '904989064999',
    projectId: 'whatsapp-backend-ad7cc',
    storageBucket: 'whatsapp-backend-ad7cc.appspot.com',
    iosClientId: '904989064999-k92fjakqn3in5nmhv542pcb0ud82jbh6.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappUi',
  );
}
